import '../packages/context/__tests__';
import '../packages/element/__tests__';
import '../packages/form/__tests__';
import '../packages/lit-html-renderer/__tests__';
import '../packages/redux/__tests__';
import '../packages/router/__tests__';
import '../packages/storeon/__tests__';
import '../packages/styles/__tests__';
import '../packages/utils/__tests__';
