name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/**'
      - '!packages/**/README.md'
      - 'scripts/**'
      - 'test/**'
      - '.eslintignore'
      - '.eslintrc'
      - 'package.json'
      - 'package-lock.json'
      - 'sonar-project.properties'
      - 'tsconfig.json'
      - 'tslint.json'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/**'
      - '!packages/**/README.md'
      - 'scripts/**'
      - 'test/**'
      - '.eslintignore'
      - '.eslintrc'
      - 'package.json'
      - 'package-lock.json'
      - 'sonar-project.properties'
      - 'tsconfig.json'
      - 'tslint.json'

jobs:
  testing:
    name: 'OS: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout project code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation
        run: npm install
      - name: Testing
        run: |
          npm run test:coverage
          node scripts/convertCoveragePaths.js .coverage/lcov.info
        env:
          CI: true
      - name: Save code coverage
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}.lcov
          path: .coverage/lcov.info
  analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: testing

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout project code
        uses: actions/checkout@v1
      - name: Load ubuntu-latest code coverage
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest.lcov
          path: .coverage/ubuntu
      - name: Load macOS-latest code coverage
        uses: actions/download-artifact@master
        with:
          name: macOS-latest.lcov
          path: .coverage/macOS
      - name: Prepare build
        run: |
          npm install
          npm run build
          node scripts/convertCoveragePaths.js .coverage/macOS/lcov.info .coverage/ubuntu/lcov.info --restore
      - name: Run Sonar Scanner
        run: |
          sh scripts/sonarScanner.sh
        env:
          SONAR_SCANNER_VERSION: 4.0.0.1744
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
